# Generated by Django 4.0.4 on 2022-05-24 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buy', '0004_buy_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buy',
            name='amount',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='buy',
            name='price',
            field=models.FloatField(null=True),
        ),
    ]
